"""
Ontology Toolkit

Semantic instance model.

These classes represent graph data independently of any
serialization format (RDF, RDF-star, JSON-LD, etc.).
"""

from dataclasses import dataclass, field


# ------------------------------------------------------------
# Entity Instance
# ------------------------------------------------------------

@dataclass(slots=True)
class EntityInstance:
    """
    One node instance in the knowledge graph.
    """

    # Stable URI generated by the toolkit
    uri: str

    # Neo4j elementId (internal only)
    element_id: str

    # Class (derived from the primary Neo4j label)
    class_name: str

    # Node properties
    properties: dict[str, object] = field(default_factory=dict)


# ------------------------------------------------------------
# Relationship Instance
# ------------------------------------------------------------

@dataclass(slots=True)
class RelationshipInstance:
    """
    One relationship instance in the knowledge graph.

    Example:

        Faculty --AUTHOR_OF--> Publication

    This object stores both the original Neo4j relationship
    type and the semantic predicate that exporters should use.
    """

    # Stable URI generated by the toolkit
    uri: str

    # Neo4j elementId (internal only)
    element_id: str

    # Original Neo4j relationship type
    relationship_type: str

    # Semantic predicate (e.g. authorOf)
    predicate: str

    # Connected entity URIs
    source_uri: str
    target_uri: str

    # Relationship properties
    properties: dict[str, object] = field(default_factory=dict)


# ------------------------------------------------------------
# Semantic Graph
# ------------------------------------------------------------

@dataclass(slots=True)
class SemanticGraph:
    """
    Instance-level graph.

    This is the runtime counterpart to GraphSchema and serves as
    the canonical in-memory representation of graph instance data.
    """

    entities: list[EntityInstance] = field(default_factory=list)
    relationships: list[RelationshipInstance] = field(default_factory=list)

    @property
    def entity_count(self) -> int:
        """Return the number of entities."""
        return len(self.entities)

    @property
    def relationship_count(self) -> int:
        """Return the number of relationships."""
        return len(self.relationships)

    @property
    def is_empty(self) -> bool:
        """Return True if the graph contains no entities or relationships."""
        return len(self) == 0

    def get_entity(self, uri: str) -> EntityInstance | None:
        """
        Return the entity with the given URI, or None if not found.
        """
        return next(
            (entity for entity in self.entities if entity.uri == uri),
            None,
        )

    def entities_by_class(self, class_name: str) -> list[EntityInstance]:
        """
        Return all entities belonging to the specified class.
        """
        return [
            entity
            for entity in self.entities
            if entity.class_name == class_name
        ]

    def outgoing(
        self,
        source_uri: str,
        predicate: str | None = None,
    ) -> list[RelationshipInstance]:
        """
        Return outgoing relationships from the specified entity.

        If a predicate is supplied, only matching relationships are returned.
        """
        return [
            relationship
            for relationship in self.relationships
            if relationship.source_uri == source_uri
            and (
                predicate is None
                or relationship.predicate == predicate
            )
        ]

    def incoming(
        self,
        target_uri: str,
        predicate: str | None = None,
    ) -> list[RelationshipInstance]:
        """
        Return incoming relationships to the specified entity.

        If a predicate is supplied, only matching relationships are returned.
        """
        return [
            relationship
            for relationship in self.relationships
            if relationship.target_uri == target_uri
            and (
                predicate is None
                or relationship.predicate == predicate
            )
        ]

    def __len__(self) -> int:
        """
        Return the total number of graph elements.
        """
        return self.entity_count + self.relationship_count

    def __str__(self) -> str:
        return (
            f"SemanticGraph("
            f"entities={self.entity_count}, "
            f"relationships={self.relationship_count})"
        )