from ontology_toolkit.report.styles import get_styles


def render_page(title, body):

    return f"""<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{title}</title>

<style>

{get_styles()}

</style>

<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css">

</head>

<body>

{body}

<footer class="report-footer">

<hr>

<p>

Generated by the
<strong>Semantic Graph Toolkit</strong>

<br>

GitHub:
<a href="https://github.com/triplegem/neo4j-graph-to-ontology">
triplegem/neo4j-graph-to-ontology
</a>

</p>

</footer>

<script>
document.addEventListener("DOMContentLoaded", () => {{

    const toc = document.querySelector(".toc");
    const viewerNav = document.querySelector(".viewer-nav");

    function updateViewerNavOffset() {{

        if (!toc || !viewerNav) {{
            return;
        }}

        const styles = getComputedStyle(toc);
        const top = parseFloat(styles.top) || 0;

        const offset = toc.offsetHeight + top + 16;

        document.documentElement.style.setProperty(
            "--viewer-nav-top",
            `${{offset}}px`
        );
    }}

    updateViewerNavOffset();

    window.addEventListener("resize", updateViewerNavOffset);

    if (!toc) {{
        return;
    }}

    const stickyPoint = toc.offsetTop;

    let compact = false;

    window.addEventListener("scroll", () => {{

        const shouldCompact = window.scrollY > stickyPoint;

        if (shouldCompact !== compact) {{

            compact = shouldCompact;

            toc.classList.toggle("compact", compact);

            updateViewerNavOffset();

        }}

    }});

}});
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-turtle.min.js"></script>

</body>

</html>
"""